pipeline {
    agent any
    environment {
        REGISTRY="registry-hacathon.oss.net.bd"
        dockerRegistryCredential='registry-hacathon.oss.net.bd'
        dockerImage = ''
        DOCKER_REGISTRY_URL="https://$REGISTRY"
        DEPLOYMENT_ENV="dev"
        IMAGE_CREATED_BY="jenkins"
        CONFIG_MAP="lung-cancer-configmap"
	    SECRET_REF="lung-cancer-secret"
        PROJECT_NAME="lung-cancer"
        SERVICE_NAME="lung-cancer-portal"
        NAMESPACE="test-2"
        DEPLOYMENT_ENV_VERSION="$NAMESPACE"

        PROJECT_LOCATION="$JENKINS_DATA_LOCATION/workspace/$JOB_NAME"
        //IMAGE_VERSION="$BUILD_NUMBER-$IMAGE_CREATED_BY-$GIT_TAG"
        //IMAGE_REPOSITORY_NAME="$REGISTRY/$PROJECT_NAME/$SERVICE_NAME"
        //DOCKER_TAG="$REGISTRY/$PROJECT_NAME/$SERVICE_NAME/$IMAGE_VERSION"

        IMAGE_VERSION="$BUILD_NUMBER-$IMAGE_CREATED_BY-$DEPLOYMENT_ENV_VERSION"
        IMAGE_REPOSITORY_NAME="$REGISTRY/$PROJECT_NAME/$SERVICE_NAME"
        DOCKER_TAG="$IMAGE_REPOSITORY_NAME:$IMAGE_VERSION"

        DEPLOYMENT_DIRECTORY="./deploy/$DEPLOYMENT_ENV"

        //k8s cluster specific configuration
        K8S_SERVICE_NAME="$PROJECT_NAME"
        K8S_CHANGE_CAUSE="$IMAGE_VERSION"

        DEPLOYMENT_TIMEOUT="500s"
        
        NODEPORT="30100"
		
	    }

    stages {

     
     stage('Building Docker image') { 
            steps { 
                script { 
                    dockerImage = docker.build("$DOCKER_TAG", "-f ./frontend/Dockerfile .")
                }
                sh '''
                docker images|grep $PROJECT_NAME
                '''
            } 
        }

      stage('Push docker image') {
            steps{
                script {
                    docker.withRegistry( "$DOCKER_REGISTRY_URL", dockerRegistryCredential ) {
                        dockerImage.push()
                        sh "docker images|grep $PROJECT_NAME"
                    }
                    
                }
            }
        }
     


     stage('Deleted image After upload to Registry') {
            steps {
                echo "Cleaning local docker registry $DOCKER_TAG image"
                sh 'docker rmi $DOCKER_TAG'
            }
        }



    }
}
